### ISSUE TITLE
Consider 'Pass' as a possible value for first or second action vice fam:Action 

### ISSUE THREAD

**Issue by jmbrule** [oasis-open/openc2-custom-aps#7]
Upon review of the Trend Micro schema I noted that a custom action was defined.  'Pass'.    I see pass more like a command option, here is my logic or lack thereof:  When you are doing a scan for malware, when you discover it, you will want to do something with the file such as delete, contain, or simply pass over it. 
IN some ways, the FAM actuator is more interesting than the SLPF because of the options that one would do upon an event of sorts.  FAM options are in fact other actions but I would argue that in the context of a FAM SCAN, the first_action and second_action is analogous to the SLPF drop_process.  In the SLPF, when you deny a five-tuple and you set the drop_process argument, you may drop it, do a reject or do a complete.   In FAM, when you find an evil file, you can set the first_action to contain, delete or pass.  
In the context of the SCAN action in the FAM profile, we are talking about possible values for a FAM argument, not OpenC2 actions embedded in the arguments field of the SCAN <target> command.  
Well that was clear as mud, hopefully someone can figure out what I was trying to say

**Comment by davaya** [comment]
OBE - Trend Micro will be incorporating FAM into a comprehensive endpoint profile.
